### ISSUE TITLE
Member profiles do not line up when profile information is missing

### ISSUE THREAD

**Issue by nickytonline** [Virtual-Coffee/open-source#15]
## Description

On the members page, if there is missing GitHub profile information, the member's profile becomes oout of line with the rest of the members

## Solution

Take into account empty member profile information when spacing the member profile information.

## Expected Behaviour

All member profiles should line up properly.

## Screenshots

Here is a screenshot of the issue.

![image](https://user-images.githubusercontent.com/833231/94967753-b7990e00-04cd-11eb-84a7-0eef3bad6733.png)

## Resources

* [Flexbox](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox)
* [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid)

**Comment by danieltott** [comment]
@nickytonline thank you so much for the issue! This is actually [handled in the virtualcoffee.io repo](https://github.com/Virtual-Coffee/virtualcoffee.io/issues/41) 

But this also brings to light some improvements we can make to make this more clear to everyone 🙏

**Comment by nickytonline** [comment]
Ooops, I thought I was in the right repo. My bad. 🙃
