### ISSUE TITLE
Rename master branch to main. 

### ISSUE THREAD

**Issue by saramccombs** [Virtual-Coffee/open-source#2]
Rename master branch to main. 

https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by tkshill** [comment]
With the _main_ branch now our official source, can we safely remove the _master_ branch?

**Comment by saramccombs** [comment]
I think so. My hesitation to delete the master branch was due to the “unexpected consequences” that were mentioned. I wanted to give it just a few more days to ensure the process moved forward without a hitch before permanently deleting the branch. (Not that it was really that substantial in the first place.)

**Comment by saramccombs** [comment]
I’ll delete then close this issue.

**Comment by tkshill** [comment]
That makes sense. I am terrified of git shenanigans so better safe than sorry was probably the right way to go.

**Comment by saramccombs** [comment]
Deleted. Closing issue.
