### ISSUE TITLE
Creating a file to store resources

### ISSUE THREAD

**Issue by tkshill** [Virtual-Coffee/open-source#6]
For now we're looking at a simple file or folder to hold the links discussed in the virtual coffee slack channel. Something along the lines of a _resources.md_

If it starts off as just a data dump that's okay, but hopefully soon we can settle on a simple template with instructions on how to update the list. 

A good start would be just if we had the link and the associated person who shared it.

e.g.
[Step by Step to contributing on github](https://www.dataschool.io/how-to-contribute-on-github/) - Submitted by TK

**Comment by danieltott** [comment]
Handled by https://github.com/Virtual-Coffee/open-source/pull/13
